[WIP] 466 add log file v4
plocket/docassemble-cucumber pull request #517
Opened 2022-02-17 19:59 UTC by mcdonaldcarolyn

Created log.txt and git hub artifact for reports

2022-02-18 23:23 UTC, plocket requested changes
Great progress! A couple things to add/change that I completely forgot to describe to you. Some of them are nitpicky and if you don't get to them, I'll approve the PR anyway.

When the major items are taken care of, I'll take update the changelog because it has a merge conflict from other branches that were recently merged.

2022-02-18 23:23 UTC, plocket commented on lib/scope.js
> +    fs.appendFileSync('log.txt', `Report:\n type: ${ type }, value: ${ value }`);
This is my typo from my console log, but it'd be generous of you to fix it - I have a space between the `\n` and "type". This is what I'd love it to be:

```suggestion
    fs.appendFileSync('log.txt', `Report:\ntype: ${ type }, value: ${ value }`);
```

2022-02-28 18:02 UTC, mcdonaldcarolyn commented on lib/steps.js
> +  fs.writeFileSync('log.txt', " ");
Yes no problem

2022-03-02 14:01 UTC, plocket approved these changes
Looks great! Thank you!

2022-03-02 14:02 UTC, merged