526 change logfile to debug_log.txt v4
plocket/docassemble-cucumber pull request #538
Opened 2022-03-29 23:51 UTC by mcdonaldcarolyn

2022-03-31 21:01 UTC, plocket approved these changes
Thank you for the improvement! I left two possible improvements that we can do in future if needed. If you want to do them now, let me know when you're done and I'll review again.

Also, if you could link this PR to issue #526, that would be useful.

Thank you!

2022-03-31 21:01 UTC, plocket commented on .github/workflows/test_tests.yml
> +      - name: debug_log artifact
A possible improvement could be changing the name to something like "upload debug_log". A bit more friendly to humans who don't know what "artifact" means in this context.

2022-03-31 21:01 UTC, plocket commented on .gitignore
> +debug_log.txt
We do still want the slash at the start.

2022-03-31 21:28 UTC, mcdonaldcarolyn commented on .github/workflows/test_tests.yml
> +      - name: debug_log artifact
great idea!

2022-03-31 21:29 UTC, mcdonaldcarolyn commented on .gitignore
> +debug_log.txt
ok, got it. Thank you for the helpful feedback!

2022-04-01 18:02 UTC, plocket requested changes
After the next comment is resolved I think we're good to go!

2022-04-01 18:02 UTC, plocket commented on log.txt
> +Report:
Just need to delete this file and then I think we're good!

2022-04-02 01:15 UTC, plocket commented
Oh, also link #526 if you have the time.

2022-04-04 18:04 UTC, mcdonaldcarolyn commented
Closes #526

2022-04-05 13:21 UTC, plocket approved these changes
Looks great! Thanks for fine-tuning!

2022-04-05 13:21 UTC, merged